name: Deploy Backend

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: BE-runner

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Backend .env file
        run: |
          cat > order-management-BE/.env <<EOF
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          PORT=${{ secrets.PORT }}
          URL=${{ secrets.URL }}
          EOF

      - name: Stop existing containers
        run: |
          docker compose down || true

      - name: Build and start services
        run: |
          docker compose up -d --build

      - name: Clean up unused Docker images
        run: |
          docker image prune -f

      - name: Check container status
        run: |
          docker compose ps
